In [1]:
import torch
from torch import nn

In [2]:
device = torch.device('cuda:0')

In [3]:
class Embeddings(nn.Module):
    "The embedding module from word, position and token_type embeddings."
    def __init__(self):
        super().__init__()
        self.tok_embed = nn.Embedding(100, 4) # token embedding
        self.pos_embed = nn.Embedding(100, 4) # position embedding
#         self.seg_embed = nn.Embedding(2, 4) # segment(token type) embedding

        self.norm = nn.LayerNorm(4)
        self.drop = nn.Dropout(0.1)

    def forward(self, x):
        seq_len = x.size(1)
        pos = torch.arange(seq_len, dtype=torch.long, device=x.device)
        print(pos)
        pos = pos.unsqueeze(0).expand_as(x) # (S,) -> (B, S)
        print(pos)
        e = self.tok_embed(x) + self.pos_embed(pos)
        print(self.tok_embed(x).size(), self.pos_embed(pos).size())
        return self.drop(self.norm(e))

In [17]:
x1 = torch.zeros((1, 10)).to(device).long() 
x1[0, 3] = 1
x2 = torch.zeros((1, 10)).to(device).long()
x2[0, 6] = 1
x = torch.stack((x1, x2))
x

tensor([[[0, 0, 0, 1, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 1, 0, 0, 0]]], device='cuda:0')

In [5]:
emb = Embeddings().to(device)

In [6]:
y = emb(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], device='cuda:0')
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], device='cuda:0')
torch.Size([2, 10, 4]) torch.Size([2, 10, 4])


In [7]:
y.size()

torch.Size([2, 10, 4])

In [8]:
y

tensor([[[-0.7368,  1.7552,  0.1218, -1.1402],
         [-1.3267,  1.2296,  0.0000, -0.8629],
         [-0.1025,  1.6025,  0.0358, -1.5357],
         [ 0.0000, -1.6171,  0.7571, -0.4007],
         [-0.7953,  1.5004,  0.5977, -1.3028],
         [-1.4587,  0.0000,  1.1395, -0.6951],
         [-1.2745,  1.5440,  0.5337,  0.0000],
         [-0.3649,  1.8898, -0.9507, -0.5742],
         [-0.2391,  1.5931,  0.1675, -1.5215],
         [-1.6614,  0.8670,  1.1424, -0.3481]],

        [[-0.7368,  1.7552,  0.1218, -1.1402],
         [-1.3267,  1.2296,  0.9600, -0.8629],
         [-0.1025,  0.0000,  0.0358, -1.5357],
         [-1.4374,  0.6122,  1.4511, -0.6259],
         [ 0.0000,  1.5004,  0.5977, -1.3028],
         [-1.4587,  1.0143,  1.1395, -0.6951],
         [ 1.7939,  0.0000,  0.0000, -0.2812],
         [-0.3649,  0.0000, -0.9507, -0.5742],
         [-0.2391,  1.5931,  0.1675, -1.5215],
         [-1.6614,  0.8670,  1.1424, -0.3481]]], device='cuda:0',
       grad_fn=<FusedDropoutBackward>)

In [18]:
x.size()

torch.Size([2, 1, 10])

In [30]:
_x = x.float() @ x.transpose(1, 2).float()

In [31]:
_x.size()

torch.Size([2, 1, 1])

In [32]:
_x

tensor([[[1.]],

        [[1.]]], device='cuda:0')

In [33]:
_x.contiguous()

tensor([[[1.]],

        [[1.]]], device='cuda:0')